name: Java CI with Gradle1

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
